### ISSUE TITLE
Transfer ownership of repository?

### ISSUE THREAD

**Issue by rbewley4** [Eclipse-Phase-Unofficial/ep-character-creator#101]
I own this repository, but I rarely contribute to it. I am willing to transferring ownership to another user or organization in order to give those who do contribute greater control. If that is something you want, just ask. Otherwise, feel free to close this issue.

**Comment by EmperorArthur** [comment]
Sounds like an organization is in order.  That should let multiple people, including you, participate at their own pace.

I've made an organization [here](https://github.com/Eclipse-Phase-Unofficial), and invited you.

Once you've accepted the invitation, you can follow the instructions [here](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) to transfer the repository.

**Comment by rbewley4** [comment]
The repository has been transferred to Eclipse-Phase-Unofficial.

**Comment by EmperorArthur** [comment]
Sorry, Hurricane has prevented me from taking a look at this for a bit.

I'm glad this is all working, and I look forward to working with you.
