### ISSUE TITLE
Application time-out

### ISSUE THREAD

**Issue by Reshy** [Eclipse-Phase-Unofficial/ep-character-creator#102]
Seems like whenever I step away from the application for more than a few minutes it errors out, necessitating reloading the app again, and then reimporting the JSON.  Is there any fix for that?

**Comment by EmperorArthur** [comment]
It turns out that despite having PHP7 installed, apache was using PHP5!

Hopefully by removing the old version, and switching over to PHP7 things will work better, and sessions will now be 30 minutes.
