### ISSUE TITLE
Missing Enhancement from Guard Deluxe morph

### ISSUE THREAD

**Issue by ktwhittenburg** [Eclipse-Phase-Unofficial/ep-character-creator#93]
Looking at the morph ID pdf, Guards are supposed to have the Synthetic Mask enhancement. In this creator, the Guard morph does, but the Guard Deluxe morph does not.

ETA: This problem extends to other enhancements that Guard Deluxe is supposed to have as base gear. In addition to Synthetic Mask, they are also missing T-ray Emitter and Puppet Sock.

**Comment by EmperorArthur** [comment]
Issue is fixed in latest feature branch.  I will close this when it is pushed to production.

**Comment by EmperorArthur** [comment]
Fixed in V1.50.  Which is located at https://cd-net.net
